# Site settings
name: Hieu Tran
title: Hieu Tran | NLP Enthusiast
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://heraclex12.github.io/
baseurl: ''
email: heraclex12@gmail.com
cover: https://heraclex12.github.io/img/og.png
logo: https://heraclex12.github.io/img/emojis/technologist.png
resume: https://heraclex12.github.io/Hieu_resume.pdf
social:
  - title: email
    url: mailto:heraclex12@gmail.com
  - title: twitter
    url: https://twitter.com/tth_razent
  - title: github
    url: https://github.com/heraclex12
  - title: linkedin
    url: https://www.linkedin.com/in/hieutt0

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
